feature/AGED-35/page-de-contact-support
gedoiseteam/gedoise-android-app pull request #31
Opened 2024-10-10 07:32 UTC by zykogithub

regarde si la page contact te plait sinon je l'améliore
Je garde la branche test au cas où et cette version c'est celle où on passe par un Intent pour envoyer le mail. Donc le sujet et le contenu est envoyé à la boite maill externe avec l'adresse où il faut envoyer, il suffira à l'utilisateur d'appuyer sur le boutton envoyer de la boîte mail externe

2024-10-16 14:55 UTC, mourchidimfoumby commented
J'ai ajouté pas mal de commentaires si tu veux en discuter tu me dis.

2024-10-21 14:19 UTC, mourchidimfoumby requested changes

2024-10-21 14:42 UTC, zykogithub commented on app/src/main/java/com/upsaclay/gedoise/presentation/profile/support/SupportScreen.kt
> +        TODO("résoudre le problème de l'objet context")
si je l'ai résolu du coup, sinon j'aurai pas fait de pull request

2024-10-21 14:44 UTC, zykogithub commented on app/src/main/java/com/upsaclay/gedoise/presentation/profile/ProfileScreen.kt
> +// pourquoi ?
je crois que je me demandais pourquoi tu avais mis en commentaire

2024-10-21 14:45 UTC, zykogithub commented on app/src/main/java/com/upsaclay/gedoise/presentation/profile/ProfileScreen.kt
> +                    .fillMaxSize()
où ?
tu peux me citer les lignes car dans la preview je ne vois pas quel élément je dublique

2024-10-21 14:49 UTC, mourchidimfoumby requested changes

2024-10-21 14:49 UTC, mourchidimfoumby commented on app/src/main/java/com/upsaclay/gedoise/presentation/profile/ProfileScreen.kt
> +// pourquoi ?
Si tu vois des parties de code en commentaire ce sont des éléments implémenté antérieurement qui ne sont pas utilisé dans le code actuel mais utilisable dans le futur.

2024-10-21 14:49 UTC, mourchidimfoumby commented on app/src/main/java/com/upsaclay/gedoise/presentation/profile/ProfileScreen.kt
> +                    .fillMaxSize()
La ligne d'en dessous

2024-10-30 01:53 UTC, zykogithub commented
j'ai fait un nouveau push sur la branche, si tu peux review mes changements et me dire ce que tu en penses

2025-02-17 18:57 UTC, closed without merging